name = "yoyaku-viewer"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
# Set GOOGLE_SHEETS_API_KEY here OR use `npx wrangler secret put GOOGLE_SHEETS_API_KEY`
# Example: GOOGLE_SHEETS_API_KEY = "AIzaSy..."
